print("Hello! My name is Creeper.")
print("I was created in 2009.")
print("Please, remind me your name.")
your_neme = input()
print(f"What a great name you have, {your_neme}!")
print("Let me guess your age.")
print("Enter remainders of dividing your age by 3, 5 and 7.")
remainder3 = int(input())
remainder5 = int(input())
remainder7 = int(input())
age_f = (remainder3 * 70 + remainder5 * 21 + remainder7 * 15) % 105
print(f'Your age is {age_f}; thats a good time to start programming!')
